"""Shared utilities for the AI Agent Hub Streamlit app."""

from .app_state import (
    API_URL,
    LANDING_IMG_DIR,
    RUNS_DIR,
    TMP_FEEDBACK_DIR,
    ensure_session_defaults,
    apply_global_styles,
    apply_form_styles,
    load_image,
    save_uploaded_image,
    render_image_tag,
    show_footer,
)

from .credit import (
    BANNED_NAMES,
    PII_COLS,
    CURRENCY_OPTIONS,
    ensure_currency_defaults,
    dedupe_columns,
    scrub_text_pii,
    drop_pii_columns,
    strip_policy_banned,
    append_user_info,
    save_to_runs,
    try_json,
    safe_json,
    fmt_currency_label,
    generate_raw_synthetic,
    generate_anon_synthetic,
    to_agent_schema,
    render_credit_dashboard,
    fetch_production_meta,
    build_training_payload,
)

from .landing import AGENT_CATALOG, render_agent_catalog
from .navigation import PAGES, render_navbar, set_active_page

__all__ = [
    "API_URL",
    "LANDING_IMG_DIR",
    "RUNS_DIR",
    "TMP_FEEDBACK_DIR",
    "ensure_session_defaults",
    "apply_global_styles",
    "apply_form_styles",
    "load_image",
    "save_uploaded_image",
    "render_image_tag",
    "show_footer",
    "BANNED_NAMES",
    "PII_COLS",
    "CURRENCY_OPTIONS",
    "ensure_currency_defaults",
    "dedupe_columns",
    "scrub_text_pii",
    "drop_pii_columns",
    "strip_policy_banned",
    "append_user_info",
    "save_to_runs",
    "try_json",
    "safe_json",
    "fmt_currency_label",
    "generate_raw_synthetic",
    "generate_anon_synthetic",
    "to_agent_schema",
    "render_credit_dashboard",
    "fetch_production_meta",
    "build_training_payload",
    "AGENT_CATALOG",
    "render_agent_catalog",
    "PAGES",
    "render_navbar",
    "set_active_page",
]
